theforeman/foreman-tasks

- app/controllers/foreman_tasks/api/tasks_controller.rb
- config/routes.rb
- lib/foreman_tasks/engine.rb
for use w/ 'hammer task resume'
> refs #10730 - adds /tasks/bulk_resume

- app/models/foreman_tasks/task/dynflow_task.rb
- lib/foreman_tasks/dynflow.rb
- test/factories/task_factory.rb
- test/unit/task_test.rb
> Fixes #8725 - consistency check on task data after executor start

- app/controllers/foreman_tasks/api/tasks_controller.rb
> Refs #10730 - find_each doesn't seem to work on string-based ids

- config/routes.rb
- foreman-tasks.gemspec
- lib/foreman_tasks.rb
- lib/foreman_tasks/dynflow.rb
- lib/foreman_tasks/dynflow/configuration.rb
- lib/foreman_tasks/dynflow/daemon.rb
- lib/foreman_tasks/dynflow/persistence.rb
Depends on https://github.com/Dynflow/dynflow/pull/139 (merged and released in dynflow 0.8.0)
> Refs #10962 - Convert foreman-tasks to use new dynflow version

- app/lib/actions/proxy_action.rb
Especially the time it happened.
> Refs #11895 - Include more information on the connection exception

- app/models/foreman_tasks/triggering.rb
Also, add attr_accessilble to work better with rails 4.
> Refs #10755 - fix setting time in the future (was defauling to Time.now)

- lib/foreman_tasks/engine.rb
Otherwise you get this in packages:
```
cannot load such file -- uglifier (in /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.7.8/app/assets/javascripts/trigger_form.js)
```
> fixes #13029 - ensure assets are precompiled

- foreman-tasks.gemspec
Depends on:
This allows to set a `present` middleware to filter the data that are
shown to the user. To use it, one needs to define a `present`
middleware:
class MyMiddleware < ::Dynlfow::Middleware
def present
action.output['password'] = '******'
pass
end
end
and then load the middleware, either globally:
initializer "my_plugin.set_dynflow_middlewares", :before => :finisher_hook do
ForemanTasks.dynflow.config.on_init do |world|
world.middleware.use MyMiddleware
end
end
or inside action (or parent action) to be used with:
class MySecretAction < Dynflow::Action
middleware.use MyMiddleware
end
This should affect all the input/output data displayed to user: either
in tasks details or dynflow conosle, but should not affect the
execution.
> Fixes #15624 - support for filtering data in presentation

- README.md
- lib/foreman_tasks/tasks/cleanup.rake
- lib/foreman_tasks/tasks/export_tasks.rake
> Fixes #14487 - Export filtered tasks in csv format

- app/views/foreman_tasks/tasks/_running_steps.html.erb
- foreman-tasks.gemspec
Second commit solves this issue in a bit cleaner way, but requires https://github.com/Dynflow/dynflow/pull/196
> Fixes #16113 - Display tasks in planning state properly

- extra/dynflow-debug.sh
Counterpart for https://github.com/Katello/katello-packaging/pull/329
> Refs #18231 - task export moved to dynflow

- app/lib/actions/action_with_sub_plans.rb
- app/lib/actions/bulk_action.rb
this was originally fixed in https://github.com/theforeman/foreman-tasks/pull/229/commits/1066089b21ef592c6023a2d16fc6eac15336d0da and got lost during rebasing
> Fixes #18963 - Fix wrong rebase

- lib/foreman_tasks/dynflow/daemon.rb
Remove unnecessary method length cop disabling
> Fix rubocop

- app/models/foreman_tasks/task.rb
has no effect until https://github.com/theforeman/foreman/pull/4030 is merged but does not do any harm without
> Fixes #20136 - ignore create permission authorization

- lib/foreman_tasks_core/runner/dispatcher.rb
- lib/foreman_tasks_core/ticker.rb
> Fixes #20182 - Handle clock ticking more efficiently

- app/models/foreman_tasks/task/summarizer.rb
- app/views/foreman_tasks/tasks/dashboard/_tasks_status.html.erb
Added column showing last task start time and removed successful tasks
from the list since they are not interesting
> Fixes #20341 - status widget shows better info

- app/controllers/foreman_tasks/tasks_controller.rb
- app/lib/actions/proxy_action.rb
- app/models/foreman_tasks/task/dynflow_task.rb
- config/routes.rb
- foreman-tasks.gemspec
- lib/foreman_tasks/engine.rb
requires https://github.com/Dynflow/dynflow/pull/240
> Fixes #20300 - Support for aborting proxy tasks

- config/foreman-tasks.yaml.example
- lib/foreman_tasks/cleaner.rb
- lib/foreman_tasks/dynflow/configuration.rb
- lib/foreman_tasks/tasks/cleanup.rake
- test/unit/cleaner_test.rb
includes https://github.com/theforeman/foreman-tasks/pull/271 and adds tests on top. I needed to break it up into more functions to ease writing tests.
> Fixes #20352 - Backup deleted tasks

- app/lib/actions/foreman/host/import_facts.rb
- app/models/foreman_tasks/concerns/host_action_subject.rb
This code was interfering with https://github.com/theforeman/foreman/pull/3649
> Fixes #19699 - Removed import_host monkey patch

- lib/foreman_tasks/engine.rb
the requirement was introduced by https://github.com/theforeman/foreman-tasks/pull/280
> Refs #20917 - bump Foreman requirements

- foreman-tasks.gemspec
- test/controllers/api/recurring_logics_controller_test.rb
- test/controllers/api/tasks_controller_test.rb
- test/factories/recurring_logic_factory.rb
- test/factories/task_factory.rb
- test/factories/triggering_factory.rb
- test/foreman_tasks_test_helper.rb
- test/helpers/foreman_tasks/tasks_helper_test.rb
- test/unit/actions/action_with_sub_plans_test.rb
- test/unit/cleaner_test.rb
- test/unit/dynflow_console_authorizer_test.rb
- test/unit/proxy_selector_test.rb
- test/unit/recurring_logic_test.rb
- test/unit/task_test.rb
- test/unit/triggering_test.rb
FactoryGirl is now FactoryBot
factory_girl_rails is now factory_bot_rails
Requires theforeman/foreman#4935
Do not merge before Nov 1
> Fixes #21461 - s/FactoryGirl/FactoryBot/g + rubocop

- lib/foreman_tasks/cleaner.rb
- test/unit/cleaner_test.rb
> Fixes #22915 - Make the cleaner clean orphaned dynflow plans

- app/lib/actions/middleware/keep_current_taxonomies.rb
- test/lib/actions/middleware/keep_current_taxonomies_test.rb
- test/lib/actions/middleware/keep_current_user_test.rb
First middleware tests of foreman-tasks!
> Refs #22969: Add keep_current_* midware tests

- README.md
The task name has changed since it was moved to core
> Fix dynflow-executor task in README

- README.md
... I hope, I got the versions right. Please double check.
> readme: add compatibility chart

- app/lib/actions/middleware/keep_current_taxonomies.rb
- app/lib/actions/middleware/keep_current_user.rb
- foreman-tasks.gemspec
> Fixes #23849 - Restore current user+taxonomies when running hooks

- README.md
- app/controllers/foreman_tasks/api/tasks_controller.rb
- app/controllers/foreman_tasks/tasks_controller.rb
- app/models/foreman_tasks/task.rb
- app/models/foreman_tasks/task/dynflow_task.rb
- foreman-tasks.gemspec
- test/foreman_tasks_test_helper.rb
- test/support/dummy_active_job.rb
- test/unit/cleaner_test.rb
- test/unit/task_test.rb
See the commit messages for details
> Various fixes related to delayed active jobs

- test/controllers/api/tasks_controller_test.rb
> remove test_attributes

- foreman-tasks.gemspec
- lib/foreman_tasks/engine.rb
> Fixes #25110 - Run on_init hooks for client worlds

- app/lib/actions/base.rb
- test/controllers/api/tasks_controller_test.rb
- test/foreman_tasks_test_helper.rb
- test/unit/actions/recurring_action_test.rb
- test/unit/recurring_logic_test.rb
By waiting for specific event to happen
> Fix intermittent task controller failures

- test/unit/task_test.rb
Tests started failing after merging
https://github.com/Dynflow/dynflow/pull/319
> Refs #22602 - remove non-uuid value dynflow-related id

- lib/foreman_tasks/cleaner.rb
Inspired by https://access.redhat.com/solutions/2755731
> Fixes #22915 - optimized orphaned tasks query

- webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.scss
- webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.stories.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/__snapshots__/ScheduledTasksCard.test.js.snap
- webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.scss
- webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.stories.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCardHelper.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/__snapshots__/StoppedTasksCard.test.js.snap
Removed the stopped card colors and added icons
Removed scheduled card icon and added "Total"
> Refs #26343 - change the look of stopped and scheduled cards

- extra/dynflow-debug.sh
> Fixes #26415 - debug export ordered now

- app/controllers/foreman_tasks/tasks_controller.rb
to let uniquely identify individual tasks in the export
Signed-off-by: Pavel Moravec <pmoravec@redhat.com>
> Fixes #26544 - task export to contain task uuid

- .rubocop.yml
Happy "update rubocop" day.
Not sold on this new rules move us anywhere. Suggesting to disable for now.
> Disable new Rubocop rules

- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCardHelper.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/__snapshots__/StoppedTasksCard.test.js.snap
> Refs #27081 - in stopped table clickable items are blue

- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.scss
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.scss
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutCard/TasksDonutCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutCard/TasksDonutCard.scss
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutChart/TasksDonutChart.scss
inactive cards will be grayed-out as a whole and not only part of the card is grayed out
> Refs #27081 - Gray-out unfocused cards

- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/PausedTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/__snapshots__/PausedTasksCard.test.js.snap
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/RunningTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/__snapshots__/RunningTasksCard.test.js.snap
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/__snapshots__/ScheduledTasksCard.test.js.snap
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.js
- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/__snapshots__/StoppedTasksCard.test.js.snap
@pondrejk, does this work for you?
> Fixes #27711 - Add IDs to tasks cards

- webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.js
- webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js
- webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardHelper.js
- webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardSelectors.js
- webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboard.test.js
- webpack/ForemanTasks/Components/TasksTable/TasksTable.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
- webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
- webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
- webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
- webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTable.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/index.js
- webpack/ForemanTasks/Routes/ForemanTasksRouter.test.js
- webpack/ForemanTasks/Routes/ForemanTasksRoutes.test.js
- webpack/ForemanTasks/Routes/ShowTask/__tests__/ShowTask.test.js
- webpack/ForemanTasks/Routes/__snapshots__/ForemanTasksRoutes.test.js.snap
Instead of using `window.history`
>  Refs #26346 - tasks table uses router history

- app/models/setting/foreman_tasks.rb
As theforeman/foreman#6902 got merged, we need to change the setting initialization here as well, not to initialize twice.
> Fixes #27815 - setting initialization improvement

- webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
- webpack/ForemanTasks/Components/TaskDetails/index.js
- webpack/ForemanTasks/Components/TasksDashboard/index.js
- webpack/ForemanTasks/Components/TasksTable/index.js
Just ran `npm run lint -- --fix`
> Fixes #28244 - fix linting errors

- app/lib/actions/proxy_action.rb
The RunHostsJob task failed to update the status of its Ansible sub
tasks because Ansible task is using a different proxy_action_name
to the Remote execution task.
For more information please check the bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1785902
> Fixes #29028 - RunHostsJob failed to update task status

- app/models/foreman_tasks/task.rb
- app/models/foreman_tasks/task/search.rb
- test/factories/task_factory.rb
- test/unit/task_test.rb
@adamruzicka something like that?
see also https://github.com/Katello/katello/pull/8562#discussion_r379355124
> Fix search for multiple resource_ids

- webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
- webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
Used to be cutout after 24 chars
> Fixes #29087 - Tasks should show Full name

- app/views/foreman_tasks/api/recurring_logics/base.json.rabl
- app/views/foreman_tasks/api/tasks/show.json.rabl
Needed for https://github.com/theforeman/hammer-cli-foreman-tasks/pull/43.
> Refs #29506 - Add attrs to recurring logic show

- script/travis_run_js_tests.sh
- webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/SubTasksPage.js
- webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
- webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
seems like when the `.babelrc` file was replaced by `babel.config.js`
that git diff line stop to work and therefore tests were not running.
> Fixes #29566 - Travis is not running JS tests

- app/models/foreman_tasks/task.rb
Piece of code that is necessary for correct working of https://github.com/theforeman/foreman_remote_execution/pull/453
> Fixes #28776 - Adding Jail for task model

- lib/foreman_tasks/tasks/cleanup.rake
- lib/foreman_tasks/tasks/dynflow.rake
- lib/foreman_tasks/tasks/export_tasks.rake
(cherry picked from commit b192911)
> Fixes #30145 - Make sure rake tasks run as Dynflow clients

- app/controllers/foreman_tasks/recurring_logics_controller.rb
- config/routes.rb
- lib/foreman_tasks/engine.rb
> Fixes #30623 - Add search to recurring logic table

- package.json
- webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Related to https://github.com/theforeman/foreman-js/pull/212
> Fixes #30800 - Upgrades js tests to support jest 26

- webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
- webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
- webpack/ForemanTasks/Components/TaskDetails/TaskDetails.scss
- webpack/ForemanTasks/Components/TasksTable/TasksTablePage.scss
- webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionNameCellFormatter.test.js.snap
- webpack/ForemanTasks/Components/TasksTable/formatters/actionNameCellFormatter.js
> Refs #31501 - Word wrap for name in task details and table

- app/controllers/foreman_tasks/api/tasks_controller.rb
- db/migrate/20180927120509_add_user_id.foreman_tasks.rb
> Fixes #32094 - Fix leftovers after splitting locks

- app/models/foreman_tasks/task.rb
- test/unit/task_test.rb
see also https://github.com/Katello/katello/pull/8562#discussion_r379009700
> Fixes #29223 - add latest_tasks by resource_ids

- app/graphql/types/recurring_logic.rb
- app/graphql/types/task.rb
- app/graphql/types/triggering.rb
- app/models/foreman_tasks/recurring_logic.rb
- app/models/foreman_tasks/task.rb
- app/models/foreman_tasks/triggering.rb
- lib/foreman_tasks/engine.rb
- test/graphql/queries/recurring_logic_test.rb
- test/graphql/queries/recurring_logics_query_test.rb
- test/graphql/queries/task_query_test.rb
- test/graphql/queries/tasks_query_test.rb
Adding just types as I plan to get the data via association to job invocation.
> Fixes #32720 - Add graphql types

- app/views/foreman_tasks/layouts/react.html.erb
https://github.com/theforeman/foreman/pull/8618
> Fixes #33065 - remove deprecated notifications call in rails

- app/helpers/foreman_tasks/foreman_tasks_helper.rb
- app/models/foreman_tasks/triggering.rb
I plan to pass [start_at](https://github.com/theforeman/foreman_remote_execution/pull/619/files#diff-c7a804360df9b6b127e28adfdaa63daa5fcd5af31d82886dab5e4ff4d3708baaR150) on rex side.
> Fixes #33091 - Trigger recurring logic with a delay

- README.md
Greetings,
I added the hyperlink for the Foreman-tasks manual, addressed phrasing and spelling issues.
Cheers!
> Improve README.md phrasing and added Foreman-tasks manual link

- extra/foreman-tasks-export.sh
- lib/foreman_tasks/tasks/export_tasks.rake
Spiritual successor of https://github.com/theforeman/foreman-tasks/pull/588
> Allow export_tasks to skip tasks that fail to export

- app/lib/actions/foreman/host/import_facts.rb
Host#import_facts was replaced with HostFactImporter#import_facts.
> Refs #34063 - Clean up deprecated method usage

- app/views/foreman_tasks/api/locks/show.json.rabl
- webpack/ForemanTasks/Components/TaskDetails/Components/Locks.js
- webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Locks.test.js.snap
> Fixes #34031 - Make cards on Locks tab link to things

- config/routes.rb
Companion PR to https://github.com/theforeman/foreman/pull/7153
> Fixes #28212 - Make Redis url configurable using env variable

- app/models/foreman_tasks/remote_task.rb
- test/unit/remote_task_test.rb
Leaving as separate commits, please squash before merge.
> Fixes #34447 - Fix batch triggering with multiple proxies, vol. 2

- app/lib/actions/helpers/with_delegated_action.rb
> Fixes #35217 - Allow overriding proxy action class

- app/helpers/foreman_tasks/foreman_tasks_helper.rb
- app/models/foreman_tasks/recurring_logic.rb
- app/views/foreman_tasks/api/recurring_logics/base.json.rabl
- app/views/foreman_tasks/recurring_logics/index.html.erb
Everything the UI shows should be obtainable through API as well.
> Fixes #35940 - More details in recurring_logic#index

- lib/foreman_tasks/engine.rb
> Fixes #36332 - Use plugin dsl for gettext

- app/lib/actions/check_long_running_tasks.rb
- app/lib/actions/deliver_long_running_tasks_notification.rb
Follows https://github.com/theforeman/foreman-tasks/pull/716.
> Refs #36351 - Fix wrong subject

- app/views/tasks_mailer/long_tasks.html.erb
- app/views/tasks_mailer/long_tasks.text.erb
in long running tasks email notification
> Fixes #36606 - Properly translate headers

- app/views/foreman_tasks/api/recurring_logics/base.json.rabl
> Fixes #37036 - Hide next occurrence unless RL is active

- webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
> Fixes #37605 - missing formatting in Step Canceled toast

- webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/__snapshots__/OtherInfo.test.js.snap
Needs https://github.com/theforeman/foreman/pull/10272 and to update foreman-js
> Fixes #37751 - Update to Patternfly 5

- app/models/foreman_tasks/triggering.rb
- test/factories/triggering_factory.rb
- test/unit/triggering_test.rb
Successor to #763 , hopefully with green tests
> Fixes #37938 - Reject start at in the past

- app/lib/actions/bulk_action.rb
While generating the list of action names, we allocate clases and call methods on them. Calling `BulkAction#humanized_name` raises because it has no linked task.
To test, run `rake gettext[foreman-tasks]` from foreman checkout
> Fixes #38559 - Fix store_action_names rake
