app/controllers/foreman_tasks/api/tasks_controller.rb
app/controllers/foreman_tasks/tasks_controller.rb
app/models/foreman_tasks/concerns/action_triggering.rb
app/models/foreman_tasks/task.rb
app/views/foreman_tasks/tasks/_details.html.erb
lib/foreman_tasks.rb
lib/foreman_tasks/authorizer_ext.rb
lib/foreman_tasks/dynflow.rb
lib/foreman_tasks/dynflow/configuration.rb
lib/foreman_tasks/dynflow/console_authorizer.rb
lib/foreman_tasks/engine.rb
lib/foreman_tasks/tasks/test.rake
test/controllers/api/tasks_controller_test.rb
test/factories/task_factory.rb
test/foreman_tasks_test_helper.rb
test/helpers/foreman_tasks/tasks_helper_test.rb
test/support/dummy_dynflow_action.rb
test/unit/dynflow_console_authorizer_test.rb
test/unit/task_test.rb

There are two permissions: view_foreman_tasks for viewing and 
edit_foreman_tasks for controlling them.
Two default roles are pre-seeded: Tasks Reader and Tasks Manager. Also the
Anonymous role is added a permission to see user's own tasks, to prevent the
awkward moment when a user triggers a task and can't see the progress or
status.

Fixes #4450 - authorize the tasks

---

app/lib/actions/action_with_sub_plans.rb
app/lib/actions/bulk_action.rb
app/models/foreman_tasks/lock.rb
app/models/foreman_tasks/task.rb
app/models/foreman_tasks/task/dynflow_task.rb
foreman-tasks.gemspec
test/unit/actions/action_with_sub_plans_test.rb

Bulk actions is just one of the use-cases for using sub-plans. This patch
extract the common code to be used for triggering external tasks in
general and moves that to the Dynflow.
The usage is as follows: one needs to inherit it's action from the
``Actions::ActionWithSubPlans`` and override the
``create_sub_plans`` method. The ``create_sub_plans`` will be executed in
run phase and the rest of the action will make sure that the execution of
the action will wait till the sub plan is done. It also tracks the relation
between parent and child tasks, as it already did in bulk actions.
An example code could look like this (taken from real Katello actions):
class SyncAsSubPlan < Actions::ActionWithSubPlans
input_format do
param :id, Integer
end
def plan(repository)
plan_self(:id => …

Fixes #9508 - use Dynflow sub-plans support for sub tasks and bulk actions

---

app/helpers/foreman_tasks/tasks_helper.rb
app/views/foreman_tasks/tasks/index.html.erb
test/helpers/foreman_tasks/tasks_helper_test.rb

otherwise actions with a lot of inputs cause the table column to
be very wide

Fixes #9727 - trim action details on index page

---

app/controllers/foreman_tasks/tasks_controller.rb
app/models/setting/foreman_tasks.rb
app/views/foreman_tasks/tasks/_details.html.erb
app/views/foreman_tasks/tasks/show.html.erb

also make the confirm button disabled until the user checks a
checkbox confirming they understand

Fixes #10418 - hide the unlock buttons behind a setting

---

lib/foreman_tasks/tasks/export_tasks.rake

refs #10820 - only collect 60 days of tasks by default

---

lib/foreman_tasks/dynflow/persistence.rb

The ActiveRecord active connections cleaning was sometimes called unnecessary
(in case the Dynflow persistence call was part of some bigger Rails action),
in which case the preliminary cleaning caused transactions to be committed.
We discovered that when running Katello tests, that relied on the transactions
to rollback.

Refs #10962 - enhance connection cleaning

---

lib/foreman_tasks/dynflow/daemon.rb

Use log directory instead of the tmp/pids, that the daemons use by default

Fixes #10477 - log the dynflow output to proper directory

---

app/models/foreman_tasks/task.rb

This change is to enable users to search for tasks (in UI or API) using
the parent_task_id.  This is useful if the user has the parent task
but needs to get access to it's children.
The following is an example of using API to query for tasks that have the same parent:
curl -k -u admin:password -H "Content-Type:application/json" -H "Accept:application/json,version=2" -X GET -d "{\"search\": \"parent_task_id=50b6b3ba-fa71-4a1c-840b-e1913fc5d8a6\"}" https://sat61fusor.example.com/foreman_tasks/api/tasks | json_reformat

fixes #11162 : add scoped_search parent_task_id to task model

---

app/views/foreman_tasks/tasks/index.html.erb
app/views/foreman_tasks/tasks/show.html.erb

The previous implementation often caused the browser to crash due to way how
the reloading was implemented. It also fixes the behaviour in the two-pane
mode variant.

Fixes #11092 - fix tasks reloading

---

README.md
app/lib/actions/foreman/host/import_facts.rb
config/foreman-tasks.yaml.example
lib/foreman_tasks.rb
lib/foreman_tasks/cleaner.rb
lib/foreman_tasks/engine.rb
lib/foreman_tasks/tasks/cleanup.rake
test/factories/task_factory.rb
test/unit/cleaner_test.rb
test/unit/task_test.rb

This adds a rake task for cleaning tasks based on filter and age.
Example:
rake foreman_tasks:cleanup FILTER='label = "Actions::Foreman::Host::ImportFacts"'
rake foreman_tasks:cleanup AFTER=30d
rake foreman_tasks:cleanup
By default, it only touches tasks in stopped state, this behaviour can be
customized by setting the `STATES` parameter.
To see the current configuration for the auto-cleanup, one can see
that with:
rake foreman_tasks:cleanup:config

Fixes #8144 - cleanup mechanism for tasks

---

app/controllers/foreman_tasks/api/tasks_controller.rb
app/controllers/foreman_tasks/tasks_controller.rb
app/lib/actions/proxy_action.rb
app/lib/proxy_api/foreman_dynflow/dynflow_proxy.rb
app/models/foreman_tasks/task/dynflow_task.rb
app/views/foreman_tasks/tasks/_details.html.erb
app/views/foreman_tasks/tasks/show.html.erb
config/routes.rb
db/seeds.d/60-dynflow_proxy_feature.rb
foreman-tasks.gemspec
lib/foreman_tasks/engine.rb
lib/foreman_tasks/test_extensions.rb
test/controllers/api/tasks_controller_test.rb
test/foreman_tasks_test_helper.rb
test/support/dummy_proxy_action.rb
test/unit/actions/proxy_action_test.rb

Ability to trigger action on foreman server and a corresponding action in
smart proxy, get the callback at the end and dispatch the control events (such
as cancel)
Depends on https://github.com/theforeman/smart_proxy_dynflow/pull/1

Refs #10741 - Support for smart_proxy_dynflow

---

app/models/foreman_tasks/task.rb
app/views/foreman_tasks/tasks/index.html.erb
db/seeds.d/61-foreman_tasks_bookmarks.rb

I've added sortable column `ended_at` and bookmarks that should point to potentially problematic tasks requiring user's attention.

Fixes #11674 - Bookmarks for task states

---

app/lib/actions/entry_action.rb
app/lib/actions/middleware/keep_current_user.rb
app/lib/actions/proxy_action.rb
app/lib/actions/serializers/active_record_serializer.rb
app/models/foreman_tasks/task/dynflow_task.rb
app/models/foreman_tasks/task/task_cancelled_exception.rb
app/views/foreman_tasks/tasks/_details.html.erb
db/migrate/20150817102538_add_delay_attributes.rb
lib/foreman_tasks.rb
lib/foreman_tasks/dynflow/persistence.rb
lib/foreman_tasks/triggers.rb
test/unit/cleaner_test.rb
test/unit/task_test.rb

Support for setting future time of execution and displaying info about delayed tasks

Refs #10753 - Support for setting future time of execution

---

app/helpers/foreman_tasks/tasks_helper.rb
app/models/foreman_tasks/task/dynflow_task.rb
test/helpers/foreman_tasks/tasks_helper_test.rb

On tasks index page, call only humainzed methods that are needed. Also, cache
the humanized data on first call, as the humanization might be relatively
expensive sometimes. Also, we catch all the exceptions when calling the
humanization, as it's not critical and the errors at humanization should not
prevent the user to see other task data.

Refs #11895 - optimize humanized data loading

---

app/helpers/foreman_tasks/foreman_tasks_helper.rb

basically theforeman/foreman_remote_execution#75
@stbenjam I'd still get this in to make the UI at least a bit less confusing until http://projects.theforeman.org/issues/12686 is done

Refs #12145 - Adds start_before explanation

---

db/migrate/20131205204140_create_foreman_tasks.rb

This fixes a breakage that is exposed by Rails 4.1.14 where the
primary key 'id' is set to an integer and not a string.

Fixes #13335: Set primary key properly for foreman_tasks_tasks

---

lib/foreman_tasks/dynflow.rb

Since https://github.com/Dynflow/dynflow/commit/4e3a002bd5f798090bf9d9896c5c625695c386d2#diff-35ca92bf5b10414a154a2844535ab5e9R29
we already are terminating the dynflow world in at_exit hook. Doing this
outside for Dynflow can lead to calling `exit` twice on termination finish.

Fixes #13578 - remove the at_exit hook to terminate the world

---

lib/foreman_tasks/engine.rb

The previous version override the "Reports" label of the Foreman core

Fixes #13641 - fix the ordering of the tasks menu items

---

app/models/foreman_tasks/task/dynflow_task.rb
app/models/foreman_tasks/triggering.rb
lib/foreman_tasks/dynflow/persistence.rb

Also fixes issue where displayed times were depended on local system time (having system set as gmt+2 and user timezone as gmt-11 would lead to displaying times in the gmt-9 zone.

Fixes #15091 - Handle user timezones properly

---

lib/foreman_tasks/engine.rb

On 1.13 foreman_tasks needs to be initialized before :finisher_hook,
since doing it 'after' has been deprecated for a while and will be
removed.

Fixes #15256 - Fix plugin assets deprecation

---

app/lib/actions/helpers/with_continuous_output.rb
app/lib/actions/helpers/with_delegated_action.rb
app/lib/actions/proxy_action.rb
app/services/foreman_tasks/proxy_selector.rb
foreman-tasks-core.gemspec
foreman-tasks.gemspec
lib/foreman_tasks/engine.rb
lib/foreman_tasks/tasks/test.rake
lib/foreman_tasks_core.rb
lib/foreman_tasks_core/continuous_output.rb
lib/foreman_tasks_core/runner.rb
lib/foreman_tasks_core/runner/action.rb
lib/foreman_tasks_core/runner/base.rb
lib/foreman_tasks_core/runner/command_runner.rb
lib/foreman_tasks_core/runner/dispatcher.rb
lib/foreman_tasks_core/runner/update.rb
lib/foreman_tasks_core/settings_loader.rb
lib/foreman_tasks_core/shareable_action.rb
lib/foreman_tasks_core/version.rb
test/controllers/api/tasks_controller_test.rb
test/helpers/foreman_tasks/tasks_helper_test.rb
test/support/dummy_proxy_action.rb
test/unit/actions/proxy_action_test.rb
test/unit/proxy_selector_test.rb

Refs #16058 - extract common code for remote execution and ansible

---

lib/foreman_tasks/engine.rb

To keep consistent in Foreman, we suggested to capitalize the first letter of every word in the menu.
FYI: https://github.com/theforeman/foreman/pull/3841
Thanks

Fixes #16593 - Capitalize the first letter of every world in menu.

---

lib/foreman_tasks/dynflow.rb

requires https://github.com/Dynflow/dynflow/pull/204
The only issue here would be if whole foreman was mounted on some unusual location instead of `/`

Fixes #12729 - Add dynflow navbar links

---

app/models/foreman_tasks/lock.rb
db/migrate/20161003091412_add_missing_indexes.rb

The support for defining index at column definition was added in Rails here
https://github.com/rails/rails/commit/9a0d35e820464f872b0340366dded639f00e19b9
We need to fix migrations that happened before Rails 4.2

Fixes #16779 - add missing indexes

---

app/assets/stylesheets/foreman_tasks/tasks.css.scss
app/helpers/foreman_tasks/foreman_tasks_helper.rb
app/models/foreman_tasks/task.rb
app/views/foreman_tasks/tasks/_details.html.erb
app/views/foreman_tasks/tasks/_locks.html.erb
app/views/foreman_tasks/tasks/_raw.html.erb
app/views/foreman_tasks/tasks/index.html.erb
app/views/foreman_tasks/tasks/show.html.erb

I started with some UI changes some time ago, since we now have dedicated person for it and I fail to find time for doing more I decided to send current version. Feel free to take what you find useful.
notable changes:
- owner is a link to user, reworded to triggered by
- result is only displayed if the task state is stopped, "?" otherwise, result has icon
- dates are printed more user friendly, grouped in right column
- id and label are moved to Raw tab
- progress bar changes according to patternfly
- sub tasks, parent task links converted to buttons (next to cancel)

Fixes #17290 - Usability improvements

---

app/models/foreman_tasks/concerns/action_triggering.rb
foreman-tasks.gemspec
lib/foreman_tasks/dynflow.rb
lib/foreman_tasks/dynflow/configuration.rb
lib/foreman_tasks/test_helpers.rb

Usage:
require 'foreman_tasks/test_helpers'
include ForemanTasks::TestHelpers::WithInThreadExecutor
Requires https://github.com/Dynflow/dynflow/pull/209

Fixes #17283 - helpers for test in thread executor

---

lib/foreman_tasks/test_helpers.rb

Every time somebody asked for InThreadExecutor, new connection was
created, leading to getting out of available connections eventually.
This can start causing issues when running full test suite, where mupltiple in
thread worlds are requested over time.
The easiest way to reproduce is to run:
require 'foreman_tasks/test_helpers'
10000.times { ForemanTasks::TestHelpers.test_in_thread_world }

Fixes #17283 - improve caching to test world

---

bin/dynflow-executor
lib/foreman_tasks/dynflow/daemon.rb

Now you can start multiple executors using `dynflow-executor`
or `foreman-task` and setting environment variable
`EXECUTORS_COUNT` to the desired number of executors.

Fixes #14806 - added executors_count option

---

extra/dynflow-debug.sh

extra/dynflow-debug.sh to be symlinked by foreman-packaging change
Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

Fixes #17179 - Collect dynflow logs by foreman-debug

---

app/views/foreman_tasks/tasks/_details.html.erb

The task percentage is excessively long and can be
rounded to a whole number.

Fixes #18189 - Round completed tasks percentage

---

app/models/foreman_tasks/task.rb

The scoped_search :in relations are deprecated and :relation should be
used instead to prevent it breaking when they completely drop the
feature.

Fixes #18456 - Fix scoped_search deprecations

---

lib/foreman_tasks/dynflow/daemon.rb

Hello, there is a flaw in rubygem daemons - it does not close stdout/stderr correctly when spawning subprocesses. This is file descriptor leak that is reported by SELinux.
I fixed this in the upstream version (it's pending release now), the change closes descriptors. But if you pass log_output_syslog variable, it also attempts to redirect the stdout/err to syslog on platforms which supports this (Linux...) so we don't lost error messages (in this case the root issue was sendmail).
This patch adds this flag. We need to wait until new version is released and rebase on the new version, but we can send the flag today as it will be simply ignored.

Fixes #18635 - redirect stdout/err to syslog

---

app/models/foreman_tasks/recurring_logic.rb
app/models/foreman_tasks/task.rb

Will work only with new version of scoped_search gem.
As of today, it's still only in [master](https://github.com/wvanbergen/scoped_search/commit/265f22520066c7e37e4c60adbaec3ab262f8a389).

Fixes #15922 - Added validators to id fields

---

app/models/foreman_tasks/task/dynflow_task.rb
app/views/foreman_tasks/tasks/_errors.html.erb
test/unit/task_test.rb

There are various reasons that can cause the execution plan for a task
not being available. We should still try to not fail completely at those
situations and try to show at least the data we have available in
foreman_tasks_tasks table.

Fixes #19147 - handle situations when the plan is not available

---

bin/dynflow-executor
deploy/foreman-tasks.sysconfig
foreman-tasks.gemspec
lib/foreman_tasks/dynflow.rb
lib/foreman_tasks/dynflow/daemon.rb
test/unit/config/environment.rb
test/unit/daemon_test.rb

A world will be terminated if memory limit is exceeded. This will cause the running process to be killed.
Since we are monitoring our processes, a new process will be spawned.
Relies on https://github.com/Dynflow/dynflow/pull/211

Fixes #17175 - Added support for memory monitoring.

---

app/views/foreman_tasks/tasks/show.html.erb

When starting the autorefresh we store the id of the form, which contains the uuid of current task. The refresh is cancelled if element with that id doesn't exist on page

Fixes #17347 - Stop autorefresh leaking to other pages

---

lib/foreman_tasks_core/runner/base.rb
lib/foreman_tasks_core/runner/dispatcher.rb

Fixes #20080 - Allow runners to set timeout

---

.rubocop.yml
bin/dynflow-executor

The method is not available until the ActiveSupport is fully loaded.

Fixes #20108 - don't use strip_heredoc in bin scripts

---

app/views/foreman_tasks/tasks/dashboard/_latest_tasks_in_error_warning.html.erb

Also made the table fixed with tooltips on overflow.

Fixes #20230 - Add time ended to error tasks widget

---

app/views/foreman_tasks/tasks/dashboard/_latest_tasks_in_error_warning.html.erb

There are some corner-cases where the started_at doesn't have to be specified.

Refs #20230 - handle missing started_at in tasks widget

---

extra/dynflow-debug.sh

foreman-debug extension was updated to use DB from Foreman configuration
to export foreman-tasks DB data. Before the patch connection to local
postgresql server and database 'foreman' was hard-coded.

Fixes #20914 - Connect to configured Foreman DB during export

---

config/foreman-tasks.yaml.example
deploy/foreman-tasks.cron.d

Setup to cleanup tasks older then 30 days.
While the config is in foreman-tasks.yaml it is reflected by
'foreman_tasks:cleanup:config' rake task.
The time was set to 7:45 pm so it happens before nightly syncs
and do not collide with other default tasks of Foreman

Fixes #16922 - Clean old tasks automaticaly

---

app/models/foreman_tasks/task.rb

It's now possible to search tasks by user by specifying `user = admin`:
this is an alias for `owner.login` field.

Fixes #20755 - introduce scoped search alias for user

---

lib/foreman_tasks/dynflow/configuration.rb

The previous require call for `lib/foreman` was not working
as expected.

Fixes #21081 - ensure to load foreman/dynflow/configuration

---

app/views/foreman_tasks/tasks/dashboard/_latest_tasks_in_error_warning.html.erb
app/views/foreman_tasks/tasks/dashboard/_tasks_status.html.erb

Started filed should show timestamps rather than the time it was running. Feature request was more of the timestamp in the  "latest warning/error tasks" widget.
Also as a end user, I see only the latest 5 tasks in the widget, where timestamp would be more feasible rather than when it was started. See image below

Refs #20917 - Started field should show timestamp

---

bin/dynflow-executor
bin/foreman-tasks
deploy/foreman-tasks.service
deploy/foreman-tasks.sysconfig

This partially reverts commit ecb8c5b39f6281c9c29ff3ea677b3d43002bbea2.
The only thing I've reverted was removing the init scripts themselves
and updated them to use the code, that was moved to foreman/dynflow

Revert "Fixes #18673 - Remove initialization code in favor of Dynflow"

---

app/controllers/foreman_tasks/tasks_controller.rb

redirect_to :back is a NoMethodError in the current version of Rails
used by Foreman nightly.

Fixes #22097 - Adapt to Rails 5 redirect_back

---

.rubocop.yml
app/models/foreman_tasks/recurring_logic.rb
test/foreman_tasks_test_helper.rb
test/support/dummy_task_group.rb
test/unit/recurring_logic_test.rb

Since Rails 5.1, it seems the semantic is a bit different. Also added
tests for this code path.

Fixes #22336 - use `distinct` in has_many definition

---

app/controllers/foreman_tasks/concerns/parameters/triggering.rb

KeepParams was created as a workaround for an issue in strong
params prior to Rails 5.1. It is no longer required.

Fixes #22438 - Remove KeepParams

---

lib/foreman_tasks/engine.rb

Since Foreman 1.17, we're already doing it in core. Repeating this in
here was causing race-conditions around ActiveRecord connection.

Fixes #22838 - avoid double-initialization of Dynflow runtime

---

app/lib/actions/foreman/host/import_facts.rb

Was seeing a lot of errors like:
NoMethodError: undefined method `>' for <Foreman::Version:0x....
String comparison was being attempted against the datastructure, not
the actual variable.

Fixes #22920 - Access variable, not datastructure

---

app/lib/actions/helpers/humanizer.rb

Repository synchronization task page has broken link to product details.
Similar broken link in content views task page
1. Create product and some yum-type repository in it
2. Sync that repository
3. You will be taken to page with progress bar indicating syncing status. Now
check link to product details in "Parameters: ..."

Fixes #22999 - repo synchronization task page have broken link

---

test/lib/actions/middleware/keep_current_user_test.rb

Fix a small typo in a keep_current_user middlware test description

Refs #22969: s/taxonomies/user/ in midware test

---

foreman-tasks.gemspec
lib/foreman_tasks/dynflow/configuration.rb

Require https://github.com/Dynflow/dynflow/pull/277

Fixes #22887 - update persistence initialization code

---

app/models/foreman_tasks/task.rb
app/models/foreman_tasks/task/dynflow_task.rb

The jobs created by ActiveJob would not show up properly in the tasks
list. Small adaptions should be made to allow foreman-tasks to pick up
the 'humanized' methods and display it.
Can be merged at any point, before or after: https://github.com/theforeman/foreman-tasks/pull/235

Fixes #18758 - Allow ActiveJobs to be displayed in the tasks lists

---

app/controllers/foreman_tasks/concerns/hosts_controller_extension.rb
lib/foreman_tasks/engine.rb

This was most likely missed becuase the extention module is only
included when `FOREMAN_TASKS_MONKEYS` env variable is set to true.
The module has been updated to use the new module#prepend syntax.

Fixes #23355 - Replace alias_method_chain with prepend

---

app/models/foreman_tasks/task/dynflow_task.rb

`self.label` invoked the method so `||=` never happend and the label was always calculated on demand

Fixes #23348 - Set label field properly

---

README.md

I believe the package name has changed per yum search and http://yum.theforeman.org/plugins/1.17/el7/x86_64 to:
tfm-rubygem-foreman-tasks

Package name change?

---

test/controllers/api/tasks_controller_test.rb

Port robottelo tier1 tests for foreman_task
Related Robottelo issue: https://github.com/SatelliteQE/robottelo/issues/5959
part of robottelo minitest port project: https://github.com/SatelliteQE/robottelo/projects/1

Fixes #23504 - Port robottelo tests for foreman_task

---

app/models/foreman_tasks/concerns/action_triggering.rb

`update_attributes` is an alias for `update` in Rails 5. We no longer support Rails 4, so we should use the new update methods.

Refs #23837: incl `update` in actn_trggr methods

---

lib/foreman_tasks/cleaner.rb

Allows seeing which options is the user running the cleanup script with.

Fixes #24114 - additional cleanup logging

---

app/models/foreman_tasks/concerns/action_triggering.rb

The issue is the `assign_attributes` can have already some side-effects
for sub-resources (such as parameters), and calling `super` causes
double-creation of the resources.
Changing super to `save` makes sure that we avoid this double creation.

Fixes #24493 - fix double creation of resources on host.update

---

app/lib/actions/middleware/watch_delegated_proxy_sub_tasks.rb

Before this changed we marked tasks as failed if we failed to check on
their counterparts on the smart proxy. With this change, tasks are
marked as failed only if the check succeeds.

Fixes #24909 - Mark proxy tasks as failed only if confirmed

---

app/lib/actions/bulk_action.rb
foreman-tasks.gemspec
test/unit/actions/bulk_action_test.rb

We always assumed we will get all targets from the DB. If some of
the targets were missing in the DB, we didn't create the task for
it and it lead to task counters going out of sync.
With this patch we create tasks for missing targets, but pass nil
instead of the target to it.

Fixes #25282 - Create a task for each target even if missing 

---

app/models/foreman_tasks/recurring_logic.rb
test/unit/recurring_logic_test.rb

In the method start_after we call next_occurence_time which calls @parser.next(start_time) when starting even if the start time is valid for the cron and we could very well start at the start-time itself. 
For example
cron = "* * * * *"
start_time = 12:35:00
We can start at 12:35 instead of starting at 12:36.

Fixes #25655 - Recurring Logic skips the first schedule before starting

---

foreman-tasks-core.gemspec
foreman-tasks.gemspec
lib/foreman_tasks_core/runner/dispatcher.rb
test/support/dummy_proxy_action.rb

Remove the backward compatibility with concurrent-ruby-1.0
To be merged once dynflow 1.2 is released.

Fixes #25695 - finish migration to concurrent-ruby-1.1

---

app/controllers/foreman_tasks/tasks_controller.rb

After https://github.com/theforeman/foreman/pull/6460, the original
workaround is not needed anymore.
Revert "Fixes #25427 - Make task autocomplete hit the right endpoint"
This reverts commit 1ad5207357cd22d376f1e39055de291e845c20e2.

Fixes #25958 - use foreman core fix for autocompletion endpoint

---

app/views/foreman_tasks/tasks/show.html.erb

The truncation does additional html escaping that doesn't work well
will JS's one. Since https://projects.theforeman.org/issues/25503, we
don't need to do explicit truncation in breadrumbs anymore, so we can
just get rid of it.

Fixes #26014 - don't use Rails truncate in breadcrumb

---

app/models/foreman_tasks/task/dynflow_task.rb
foreman-tasks.gemspec

ActiveJob arguments loading is broken by: https://github.com/Dynflow/dynflow/pull/317

Fixes #26352 - ActiveJob task arguments loading

---

app/lib/actions/proxy_action.rb
app/models/setting/foreman_tasks.rb

also make the default for batch size a bit smaller: the planning
of a job on host can sometimes be quite long-running process, and
the larger the batch size is, the longer we would wait until something
would start happening.

Refs #25160 - fix disabling of batch triggering

---

app/controllers/foreman_tasks/tasks_controller.rb
app/models/foreman_tasks/task.rb
app/models/foreman_tasks/task/summarizer.rb
config/routes.rb
db/migrate/20190318153925_add_task_state_updated_at.foreman_tasks.rb
lib/foreman_tasks/engine.rb
test/controllers/tasks_controller_test.rb
test/unit/summarizer_test.rb
test/unit/task_test.rb

To support showing new tasks dashboard, we need the following endpoint:
```
GET /foreman_tasks/tasks/summary/24
{ running:   { recent: 3, total: 6 },
paused:    { recent: 1, total: 3 },
stopped:   { recent: 3, total: 7,
by_result: {
success: { recent: 2, total: 4 },
warning: { recent: 1, total: 2 },
error:   { recent: 0, total: 1 },
}}
scheduled: { recent: 0, total: 3 }}
```

Fixes #26399 - add summary endpoint to support tasks dashboard

---

db/migrate/20190404132157_add_implicit_varchar_uuid_cast.rb

Before this patch foreman_tasks:cleanup rake task would fail when trying
to delete orphaned execution plans.
The error was:
```
Sequel::DatabaseError: PG::UndefinedFunction: ERROR: operator does not exist:
uuid = character varying LINE 1: ...unt" FROM "dynflow_execution_plans"
WHERE ("uuid" NOT IN (SE...
```

Refs #22602 - Add implicit casting from VARCHAR to UUID on postgres

---

app/controllers/foreman_tasks/tasks_controller.rb
app/models/foreman_tasks/task.rb
app/services/foreman_tasks/dashboard_table_filter.rb
test/foreman_tasks_test_helper.rb
test/support/history_tasks_builder.rb
test/unit/dashboard_table_filter_test.rb
test/unit/summarizer_test.rb

Support for additional params in tasks index page that influence the filtering:
* result
* state
* time_horizon (e.g. H24)
* time_mode (recent/older)
Required for https://github.com/theforeman/foreman-tasks/pull/399

Fixes #26527 - support for filtering by dashboard fields

---

.rubocop.yml
app/controllers/foreman_tasks/api/tasks_controller.rb
app/helpers/foreman_tasks/foreman_tasks_helper.rb
app/lib/actions/base.rb
app/models/foreman_tasks/task.rb
app/models/setting/foreman_tasks.rb
app/services/foreman_tasks/troubleshooting_help_generator.rb
app/services/ui_notifications/tasks.rb
app/services/ui_notifications/tasks/task_paused_admin.rb
app/services/ui_notifications/tasks/task_paused_owner.rb
app/views/foreman_tasks/tasks/_details.html.erb
db/seeds.d/30-notification_blueprints.rb
foreman-tasks.gemspec
lib/foreman_tasks/test_helpers.rb
test/foreman_tasks_test_helper.rb
test/support/dummy_dynflow_action.rb
test/unit/actions/action_with_sub_plans_test.rb
test/unit/troubleshooting_help_generator_test.rb
test/unit/ui_notifications_test.rb

This path adds notifications and troubleshooting info for pauses tasks
Troubleshooting info
--------------------
A new `TroubleshootingHelpGenerator` service class has been added to
provide troubleshooting info for paused tasks. By default, it provides
generic information explaining the situation and link to troubleshooting
documentation (in case Setting[:foreman_tasks_troubleshooting_url] is
set.
The troubleshooting_url can contain macros for foreman version and
normalized task label (the label without non-alhpanumeric characters).
For example, for the following url setting:
https://tfm.org/%{version}/tasks_troubleshooting.html#%{label}
and task 'Plugin::MyTask', the generated url would be:
https://tfm.org/1.22/tasks_troubleshooting.html#PluginMyTask
The setting is currently not set …

Fixes #26560 - paused tasks notification and troubleshooting info

---

app/lib/actions/base.rb
app/lib/actions/helpers/lifecycle_logging.rb
test/unit/actions/action_with_sub_plans_test.rb
test/unit/actions/bulk_action_test.rb

This PR adds additional logging aroudn state and result change, so that at the end, something like this gest produced in the logs:
```
2019-04-16T14:22:10 [I|bac|] Task {label: Actions::Try::Pause, id: 759dfb3d-f14a-4112-b336-e6f65e3e5eb9, execution_plan_id: 75d6e6fc-bc18-4e60-8d34-5a5a7d5dccb0} state changed: planning 
2019-04-16T14:22:10 [I|bac|] Task {label: Actions::Try::Pause, id: 759dfb3d-f14a-4112-b336-e6f65e3e5eb9, execution_plan_id: 75d6e6fc-bc18-4e60-8d34-5a5a7d5dccb0} state changed: planned 
2019-04-16T14:22:10 [I|bac|] Task {label: Actions::Try::Pause, id: 759dfb3d-f14a-4112-b336-e6f65e3e5eb9, execution_plan_id: 75d6e6fc-bc18-4e60-8d34-5a5a7d5dccb0} state changed: running 
2019-04-16T14:22:10 [I|bac|] Task {label: Actions::Try::Pause, id: 759dfb3d-f14a-4112-b336-e6f65e3e5eb9, …
```

Fixes #26626 - log task state and result changes

---

app/controllers/foreman_tasks/api/tasks_controller.rb

Without this patch, the docs for callback says something like:
```
<p>Must be an array of [[:callback, Hash, nil,
{:param_group=&gt;{:scope=&gt;ForemanTasks::Api::TasksController,
:name=&gt;:callback_target, :options=&gt;{}, :from_concern=&gt;false}},
/.../foreman-tasks/app/controllers/foreman_tasks/api/
tasks_controller.rb:152&gt;],
[:data, Hash, {:desc=&gt;“Data to be sent to the action”},
{:param_group=&gt;nil}, nil], [:callback, Hash, nil,
{:param_group=&gt;{:scope=&gt;ForemanTasks::Api::TasksController,
```
Among others, this actually causes RPM packaging to fail, because
it leaks the buildroot path inside the output.

Refs #26073 - fix params docs

---

lib/foreman_tasks/engine.rb

Otherwise, it will be filtered out and the tasks menu items will look
like they belong to the previous submenu.

Fixes #26827 - Add name to menu divider

---

webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.stories.js
webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/TasksCardsGrid.js
webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/TasksCardsGrid.stories.js
webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/__snapshots__/TasksCardsGrid.test.js.snap
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.scss
webpack/stories/index.scss

The issue is that the cards aren't shown as they should when viewport width is 1200-1500.
Please note that in the storybook the grid is rendered inside an iframe, which causes the viewport to be only the grid container, but in foreman the viewport is the whole page.
So in foreman, when the screen is 1300px this is the view:
but in the storybook:
Chose to break point of 1530px because on 1518px this is the stopped table :
and in 1530px the icons are shown as intended:

Fixes #26653 - cards-grid doesnt supports all screen sizes

---

app/lib/actions/recurring_action.rb
test/unit/actions/recurring_action_test.rb

**Issue:**
Today if a recurring logic schedules a task and the server goes down leading to the start_at of the task being in the past, whenever the server comes up, the logic picks up from the past and steps to the present time. This results in running the task as many times as it skipped during server downtime.
We want to remove these extraneous runs as one run should be enough on startup to make up for all the lost runs and then schedule the next run as per the cron.

Fixes #27091 - Skip missed scheduled tasks on server start

---

app/views/foreman_tasks/tasks/_details.html.erb

* Use `<div>` instead of `<p>`, so `<pre>` can be placed properly
* Terminate `&nbsp` (semicolon was missing)

Fixes #27234 - fix minor issues with DOM tree

---

webpack/ForemanTasks/Components/Chart/Chart.js

There is a known issue in react-c3js that can lead to the charts to
disappear due to some race condition during component unmounting/destroy
phase https://github.com/bcbcarl/react-c3js/issues/22, with this error procuder
in the console log:
```
c3.js:9223 Uncaught TypeError: Cannot read property 'data_types' of null
at ChartInternal.c3_chart_internal_fn.isPieType (c3.js:9223)
at ChartInternal.c3_chart_internal_fn.isArcType (c3.js:9234)
at ChartInternal.c3_chart_internal_fn.getArc (c3.js:4473)
at c3.js:4816
at SVGPathElement.<anonymous> (d3.js:8775)
at Object.tick [as c] (d3.js:8956)
at d3_timer_mark (d3.js:2166)
at d3_timer_step (d3.js:2147)
```
Delaying the actual destroy a bit seems to help with workarounding the
issue.

Fixes #27292 - workaround for c3 destroy issue

---

package.json

in 0eacaf8587bf88986a675f4b5acecb93cc9b58f6 we started using variables
and mixins from bootstrap-sass, but didn't add it to our dependencies

Refs #26653 - add bootstrap-sass to npm dependencies

---

.babelrc
.eslintrc
package.json
webpack/ForemanTasks/Components/TasksDashboard/Components/TasksLabelsRow/TasksLabelsRow.scss
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.scss

Migrate to use the new [@theforeman/vendor](https://github.com/theforeman/foreman-js/tree/master/packages/vendor) package from `npm`.
1. Don't forget to `rm -rf node_modules package-lock.json` and `npm i` before you test it.
2. The storybook is currently broken in master so don't expect it to work in this PR.
1. `npm run lint` should work properly with no errors.
2. `npm test` should work properly with no errors.
3. running foreman dev-server should work
4. We shouldn't notice any UI changes. especially in the scss file that changed.
Thanks

Fixes #27386 - migrate to @theforeman/vendor pkg

---

webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardHelper.js

currently on the tasks index, if you select for example stopped from the dashboard and then change a page (or anything pagination related), then the active filter (result = stopped) gets unselected.
This was caused by the JQuery that was added instead of the full page reload(which changed the URL)

Fixes #27880 - change page removes active filters

---

app/controllers/foreman_tasks/tasks_controller.rb
app/views/foreman_tasks/api/tasks/show.json.rabl
webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
webpack/ForemanTasks/Components/TasksTable/TasksTable.js
webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
webpack/ForemanTasks/Components/common/Cancel/Cancel.js
webpack/ForemanTasks/Components/common/Cancel/Cancel.test.js
webpack/ForemanTasks/Components/common/Cancel/__snapshots__/Cancel.test.js.snap
webpack/__mocks__/foremanReact/redux/actions/toasts.js

Adds a button that will cancel a task in the table (if the task can be canceled) and display a toast notification based on the answer
Based on: https://github.com/theforeman/foreman-tasks/pull/452

Fixes #27801 - Add cancel button to the tasks table

---

db/migrate/20180927120509_add_user_id.foreman_tasks.rb

Commit 2f37f56957260facecdb278fffaa1b2bd7f94eb0 changed the way how we link
tasks to users. Before we used locks, but we didn't have any constraints in
place. This could lead to a situation, where a task has a lock, which links the
task to a user, which doesn't exist anymore. If we tried to perform the
migration introduced in that commit, it would fail with foreign key violation
errors.

Fixes #28152 - Link tasks with user only if the user exists

---

app/controllers/foreman_tasks/api/tasks_controller.rb
webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js

The duration column replaces ended at column.
Duration text is in the same format as in task details.
For running tasks the duration is presented with a + (2 minutes +)
For Canceled tasks duration is presented as N\A with a tool tip that says that the task is canceled
For tasks without a start and end time, duration is presented as N\A with a tool tip about it
For sorting purposes N\A is the shortest time.

Add a duration column to the tasks table

---

webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js

This PR changes the precision of the individual task progress. The progress bar is accompanied by a numeric value as "n% Complete". (i.e.: 10.06661732050331% Complete). Reduced the precision from 14 to 2.

Fixes #27991 - Decreasing precision in Task Progress

---

webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js

uses label as fallback for tasks action name
and replaces '::' in the label so if the name is too long the name will be in a few lines instead of being on top of the next cell

Fixes #28306 - use label as fallback for tasks action name

---

app/controllers/foreman_tasks/api/tasks_controller.rb
app/controllers/foreman_tasks/tasks_controller.rb
config/routes.rb
lib/foreman_tasks/engine.rb
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.js
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js
webpack/ForemanTasks/Components/TasksDashboard/__tests__/TaskDashboard.fixtures.js
webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardActions.test.js
webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardSelectors.test.js
webpack/ForemanTasks/Components/TasksDashboard/__tests__/__snapshots__/TasksDashboardActions.test.js.snap
webpack/ForemanTasks/Components/TasksDashboard/__tests__/__snapshots__/TasksDashboardSelectors.test.js.snap
webpack/ForemanTasks/Components/TasksTable/SubTasksPage.js
webpack/ForemanTasks/Components/TasksTable/TasksTable.js
webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

adds new paths to get the info about the summary of sub tasks to use in the tasks dashboard:
`/tasks/summary/:id/sub_tasks`, 
`/summary/:id/sub_tasks/:recent_timeframe`
to the existing paths:
`/tasks/summary/`,  `/summary/:recent_timeframe`
based on: https://github.com/theforeman/foreman-tasks/pull/445

Fixes #27176 - adds subtask filter to tasks dashboard

---

app/controllers/foreman_tasks/api/tasks_controller.rb
test/controllers/api/tasks_controller_test.rb

The original error was
```
'Action failed' error (ActiveRecord::StatementInvalid): PG::AmbiguousColumn:
ERROR: ORDER BY "started_at" is ambiguous | LINE 1: ...,4))
```

Fixes #28415 - Fix PG::AmbiguousColumn error on tasks search

---

app/controllers/foreman_tasks/api/tasks_controller.rb
test/controllers/api/tasks_controller_test.rb

The original error was
PG::UndefinedColumn: ERROR: column foreman_tasks_tasks.duration does not exist |
LINE 1: ...) as duration FROM "foreman_tasks_tasks"

Fixes #28485 - Fix PG::AmbiguousColumn error on tasks search

---

webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js

in foreman tasks table
After this change:
https://github.com/theforeman/foreman/pull/7301
All the pagination info is in the response and not in the payload

Fixes #28614 - core API refactor breaks tasks pagination

---

app/controllers/foreman_tasks/api/tasks_controller.rb
test/controllers/api/tasks_controller_test.rb

This PR modifies a `'select` in the `ordering_scope` method, as previously the results would return NULLs for each task id. This was an issue for the monitor task list display, as the links generated for each task would be incorrect.

Fixes #28634 - adjusts select for nulls ids

---

package.json

Every JS test that has scss fails because of missing identity-obj-proxy package
```
Configuration error:
Could not locate module ./TaskDetails.scss mapped as:
identity-obj-proxy.
Please check your configuration for these entries:
{
"moduleNameMapper": {
"/^.+\.(png|gif|css|scss)$/": "identity-obj-proxy" 
},
"resolver": null
}
```

Fixes #28670 - missing identity-obj-proxy package for tests

---

package.json

1. It won't download `vendor` anymore
2. It will support version 3 and 4

Fixes #28666 - adds support vendor v4

---

webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js

Using  https://github.com/reduxjs/reselect so the selector/formatter for the results is not recomputed unless the result list changes.

Fixes #28319 - selectResults selector should be memorized

---

webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js

When result.label the page would crash as it can run the `replace` function on it.
Users still need something to click on in the table to get to the task so I added the result.id as a fallback if there is no label and no action

Fixes #28748 - task id fallback when there is no label

---

webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js

The url got updated and then the get tasks api was called twice - once with the right url and once with the old url.
So on the second click the old url was already the new url so when it was called twice it was called with the right info

Fixes #28822 - task Search requires clicking twice on Search

---

app/lib/actions/proxy_action.rb
app/models/foreman_tasks/remote_task.rb

Having both concurrency control and batch triggering enabled led to various issues with tasks being triggered at wrong time. This was caused by introduction of Remote Tasks and their triggering using a middleware.
This change makes sure the two mechanisms will not conflict with each other. If use_concurrency_control is passed to the proxy action, the remote tasks are created in 'external' state, meaning the batch triggering mechanism should ignore them. This allows the concurrency control to work properly.

Fixes #28095 - Make concurrency control work with batch triggering

---

webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js

When trying to click on the Cancel (or Resume) cell in the tasks table the task isn't cancelled and a toast error shows:  ' "undefined" Task cannot be cancelled at the moment.'

Fixes #29136 - unable to cancel-resume task from table

---

app/helpers/foreman_tasks/foreman_tasks_helper.rb
app/services/foreman_tasks/troubleshooting_help_generator.rb
package.json
webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js

adds the `react-html-parser` library that "Converts HTML strings directly into React components avoiding the need to use dangerouslySetInnerHTML"
and uses it for the troubleshooting

Fixes #29045 - HTML tags visible on paused task page

---

lib/foreman_tasks/engine.rb

PR is part of  [Add default descriptions to all roles added from plugins](https://projects.theforeman.org/issues/28936) task.

Fixes #28978 - Add description to plugin roles

---

webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js

Before this patch we took a float in the range from 0 to 1, turned it into a
string with desired precision and then multiplied it with 100 to get the
percentage. However, this didn't really work for all inputs, because of the well
known issues when multiplying floats.
```javascript
> x = 0.004545454545454546
0.004545454545454546
// Old way
> x.toFixed(4) * 100
0.44999999999999996
// New way
> parseFloat((x * 100).toFixed(2))
0.45
```

Fixes #29203 - Fix an edge case with excessive progress precision

---

app/controllers/foreman_tasks/recurring_logics_controller.rb
app/models/foreman_tasks/recurring_logic.rb
app/views/foreman_tasks/recurring_logics/index.html.erb
config/routes.rb
lib/foreman_tasks/engine.rb

In the index of recurring logics there should be a button to clear cancelled recurring logics

Fixes #20042 - add a clear button to recurring logics

---

app/views/foreman_tasks/api/tasks/details.json.rabl
webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/index.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

Now rails sends the `dynflow_enable_console` info to react.
fixes the snapshots for the new prop and also for the header PR

Fixes #29030 - dynflow console button is no longer disabled

---

app/controllers/foreman_tasks/api/recurring_logics_controller.rb
config/routes.rb
lib/foreman_tasks/engine.rb

recurring logics by search query, to prevent accidental removal of all the recurring logics the search is required.

Fixes #28933 - add api to delete recurring logics

---

app/controllers/foreman_tasks/api/tasks_controller.rb
config/routes.rb
lib/foreman_tasks/engine.rb

Adds a way to bulk cancel tasks using a query or an array of ids.
Return information about canceled tasks and failed to cancel tasks

Fixes #28246 - Create bulk cancel api

---

app/controllers/foreman_tasks/api/tasks_controller.rb

it doesn't filter out from the tasks list only the tasks with the relevant ids from params

Fixes #29462 - bulk tasks api doesnt work with tasks ids

---

lib/foreman_tasks/tasks/export_tasks.rake

Removes the unused verbose flag from the tar command to compress
exported tasks along with the now unnecessary output redirection to
/dev/null.

Fixes #29180 - Remove unused tar verbose flag in tasks export

---

webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTablePage.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

In tasks table when in subtasks mode the export button will export all tasks instead of only the subtasks

Fixes #29623 - export tasks doesn't filter subtasks

---

db/migrate/20200517215015_rename_bookmarks_controller.rb
webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

The bookmarks controller was changed to `foreman_tasks/tasks`
it means that users that had saved bookmarks on the original controller (`foreman_tasks_tasks`)
can't see all of their original bookmarks..
This change in the UI and the DB migration, changes to the right bookmarks controller.
old bookmark with the same name as the new bookmark
will be renamed to `#{token}_#{name}`..

Fixes #29594 - Fix wrong bookmark controller

---

webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.js
webpack/ForemanTasks/Components/TaskActions/UnlockModals.js
webpack/ForemanTasks/Components/TaskActions/__snapshots__/TaskAction.test.js.snap
webpack/ForemanTasks/Components/TaskActions/__snapshots__/UnlockModals.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModal.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalActions.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalReducer.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalSelectors.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModal.test.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModalActions.test.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/__snapshots__/ConfirmModal.test.js.snap
webpack/ForemanTasks/Components/TasksTable/TasksTable.js
webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap

Each task - row should have a force cancel button (if the task is not already stopped)
Does not include unlock for multiple tasks
depends on https://github.com/theforeman/foreman-tasks/pull/539

Fixes #29729 - add force unlock to tasks table rows

---

app/controllers/foreman_tasks/api/tasks_controller.rb
app/services/ui_notifications/tasks/task_bulk_stop.rb
config/routes.rb
db/seeds.d/30-notification_blueprints.rb
lib/foreman_tasks/engine.rb

Can bulk cancel tasks using search or tasks ids using the api `/bulk_stop/`
Response is the stopped tasks and the number of tasks in the request that were already stopped.
User also gets a notification when its done.

Fixes #29731 - Add bulk force unlock api for tasks

---

webpack/ForemanTasks/Routes/ForemanTasksRoutes.test.js

`/home/travis/build/theforeman/foreman-tasks/webpack/ForemanTasks/Routes/ForemanTasksRoutes.test.js`
`9:33 error Imported JSX component render must be in PascalCase or SCREAMING_SNAKE_CASE react/jsx-pascal-case`

Fixes #29966 - test fails in eslint for routes test

---

webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.js
webpack/ForemanTasks/Components/TaskActions/UnlockModals.js
webpack/ForemanTasks/Components/TaskActions/__snapshots__/UnlockModals.test.js.snap
webpack/ForemanTasks/Components/TaskActions/index.js
webpack/ForemanTasks/Components/TasksTable/Components/ActionSelectButton.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModal.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalActions.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModalActions.test.js
webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionSelectButton.test.js
webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ActionSelectButton.test.js.snap
webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksBulkActions.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksBulkActions.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
webpack/ForemanTasks/Components/common/ClickConfirmation/ClickConfirmation.scss
webpack/ForemanTasks/Components/common/ClickConfirmation/__snapshots__/ClickConfirmation.test.js.snap
webpack/ForemanTasks/Components/common/ClickConfirmation/index.js
webpack/ForemanTasks/Components/common/ToastsHelpers/index.js

Adds a button to bulk stop selected tasks in the tasks table.
ignores "allow dangerous actions" setting
Depends on: https://github.com/theforeman/foreman-tasks/pull/543, https://github.com/theforeman/foreman-tasks/pull/541

Fixes #29736 - Add bulk force unlock button in tasks table

---

lib/foreman_tasks/engine.rb

With the addition of `ActionButtons` which depends on foreman > 2.1.0
while running webpack compile with a bit older foreman, I got the error:
```bash
ModuleNotFoundError: Module not found: Error: Can't resolve 'foremanReact/components/common/ActionButtons/ActionButtons' in '/home/travis/.rvm/gems/ruby-2.5.8/gems/foreman-tasks-1.2.0/webpack/ForemanTasks/Components/common/ActionButtons'
```
cc @adamruzicka @MariaAga @ShimShtein

Fixes #30009 - v1.2.0 should require foreman >= 2.1.0

---

webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap

In task details, the dynflow button should open the console in a new tab

Fixes #30016 - task Open Dynflow console in a new tab

---

webpack/ForemanTasks/Components/TaskActions/TaskAction.test.js
webpack/ForemanTasks/Components/TaskActions/index.js
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsActions.test.js
webpack/ForemanTasks/Components/TaskDetails/__tests__/integration.test.js
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js
webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardActions.test.js
webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksBulkActions.test.js
webpack/__mocks__/foremanReact/redux/API.js

The API object was moved from 'foremanReact/API' to 'foremanReact/redux/API'

Fixes #30011 - Remove internal use of deprecated JS API

---

db/migrate/20200611090846_add_task_lock_index_on_resource_type_and_task_id.rb

This index leads to significant improvement in speed of certain queries
looking for locks related to a specific task and resource type.
see https://community.theforeman.org/t/slow-products-page-on-2-0/19142/ for details.

Fixes #30103 - Add index to tasks_locks table

---

lib/foreman_tasks/engine.rb

They should now be ignored by Foreman.
Companion PR to https://github.com/theforeman/foreman/pull/7727

Fixes #30054 - Do not ignore dynflow tables when dumping DB schema

---

db/migrate/20200611090846_add_task_lock_index_on_resource_type_and_task_id.rb

This index leads to significant improvement in speed of certain queries
looking for locks related to a specific task and resource type.
Also removes several indexes that are already covered by other
multi-column indexes.
(cherry picked from commit fb70a5537743f04ee0732b3de5eea99465d586bf)

[1.1.x] Fixes #30103 - Add index to tasks_locks table

---

.travis.yml

the npm cache prevent using updated versions of libraries such as `@theforeman` packages.

Fixes #30289 - disable travis npm cache

---

app/models/foreman_tasks/task/dynflow_task.rb
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js

There is a task progress decimal precision discrepancy between the UI, Hammer, and the API.  Hammer shows no decimals, the API shows many, and the UI shows at most 2.  This PR updates the UI to have the progress be an integer (no more decimals) and updates the API progress fraction to have the same precision as the UI's value.  E.g., if the task value in the UI and CLI is 83%, the progress from the API will be 0.83.

Fixes #30210 - Fix task progress dp discrepancy

---

webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

Adds ability to refresh the task states by clicking on a refresh button rather than refreshing the whole page\session.
Not sure where to place the button:
A: ![image](https://user-images.githubusercontent.com/30431079/83766692-64c95a00-a685-11ea-95be-d26d97a47959.png)
B: ![image](https://user-images.githubusercontent.com/30431079/83766699-672bb400-a685-11ea-837a-0147246d2a23.png)

Fixes #30018 - Add refresh button to tasks table

---

app/controllers/foreman_tasks/api/tasks_controller.rb
app/views/foreman_tasks/api/tasks/show.json.rabl
webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/TaskDetails.scss
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/index.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalSelectors.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModalSelectors.test.js
webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/__snapshots__/ConfirmModalSelectors.test.js.snap
webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksBulkActions.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTablePage.test.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksBulkActions.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionCellFormatter.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/selectionCellFormatter.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/actionCellFormatter.test.js
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionCellFormatter.test.js
webpack/ForemanTasks/Components/TasksTable/formatters/actionCellFormatter.js
webpack/ForemanTasks/Components/TasksTable/formatters/selectionCellFormatter.js
webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap

In tasks details and table user without can_edit permission still sees the cancel/resume buttons. if he clicks them there is a back end error as he has no permissions

Fixes #29457 - hide task actions for user with no permission

---

app/controllers/foreman_tasks/recurring_logics_controller.rb

When user enables/disables a recurring logic they will see a toast informing them of a successful action.

Fixes #30621 - add toast to recurring logic state change

---

app/views/foreman_tasks/recurring_logics/index.html.erb

Makes the ID clickable to the logic instead on the cron line

Fixes #30622 - Add ID to recurring logics table

---

package.json
webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap

'react-html-parser' was causing issues when opening task details, and as it's not maintained any more we can use `dangerouslySetInnerHTML` instead.
The html should be safe as it comes from the server

Fixes #30407 - removes unmaintained react-html-parser

---

app/assets/stylesheets/foreman_tasks/tasks.scss
app/views/foreman_tasks/layouts/react.html.erb
app/views/foreman_tasks/tasks/show.html.erb
webpack/ForemanTasks/Components/TaskDetails/TaskDetails.scss
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.scss

https://github.com/theforeman/foreman/pull/7874
`mount_react_component` should be replaced by `react_component`

Fixes #30969 - replace deprecated mount_react_component

---

webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap

`toastNotifications` prop is not used at all in PageLayout and now breaks the page

Fixes #31104 - TablePage wrong prop for toastNotifications

---

app/views/foreman_tasks/tasks/dashboard/_latest_tasks_in_error_warning.html.erb
app/views/foreman_tasks/tasks/dashboard/_tasks_status.html.erb

date_time_relative is a function that loads a react component so translating it causes showing the html instead of rendering the component

Fixes #27295 - Task widgets don't show time correctly

---

app/models/foreman_tasks/task.rb

This PR is consist of adding `action_output` to Task model and also is added to jail for usage in reports. This methods acts as proxy method for `to_json_output` in Continuous output class. These methods are requested by another PR in REX (https://github.com/theforeman/foreman_remote_execution/pull/453).

fixes #31457 - Adding method to Task jail

---

app/controllers/foreman_tasks/api/tasks_controller.rb

We changed an existing API to start require parameters it previously didn't require. This reverts the API to the previous state.

Fixes #31508 - Restore changed bulk resume api

---

webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionNameCellFormatter.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/actionNameCellFormatter.js

In the tasks table long action names overflow their cell

Fixes #31501 - Word Wrap for Long names in tasks table

---

webpack/ForemanTasks/Components/TasksTable/TasksTablePage.scss

6px margin for pagination was removed from the table in: https://github.com/theforeman/foreman/pull/8133

Fixes #31298 - Table pagination in react has extra space

---

lib/foreman_tasks/tasks/export_tasks.rake

Find each should improve batch processing a bit, I can see small boost about
1-5 % in my environment. I was also thinking removing the counter which makes
export slower on slow terminals (ssh, encryption, thousands of lines). The
patch also changed the default format from html to csv, I can change that if
you don't like it.

Improved speed of rake export task

---

webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js

On the "Monitor" -> "Tasks" page, if the user searches for a word, and then clicks the "search" button a second time to update the results, it does nothing.

Fixes #31534 - tasks search button should always reload data

---

webpack/ForemanTasks/Components/TasksTable/TasksTable.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/selectionHeaderCellFormatter.test.js.snap
webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionHeaderCellFormatter.test.js
webpack/ForemanTasks/Components/TasksTable/formatters/selectionHeaderCellFormatter.js
webpack/ForemanTasks/Components/TasksTable/index.js

This disables action dropdown and select all in tasks table for users without `edit_foreman_tasks` permission.
Requires:

Fixes #31872 - Disable bulk actions when unauthorized

---

app/lib/actions/middleware/keep_current_request_id.rb

The logging context storing middleware was being run after first round of execution plan hooks, which already wiped the logging context.

Fixes #31843 - Make sure logging context doesn't get wiped too early

---

app/models/foreman_tasks/task/search.rb
test/unit/task_test.rb

Previous fix allowed searching using IN, but only if there was a single value.
The value was treated as a string of comma-delimited numbers instead of an array
of numbers.

Refs #31773 - Fix pg syntax errors when searching by taxonomy

---

app/lib/actions/proxy_action.rb

When we're retrieving outputs of proxy actions we get back a serialized
execution plan, walk its actions and look for an action with either expected
action_class or operation name. This is somewhat flaky.
With this change we only check one field in the actions' input and that is
task_id. First action found with matching value is considered the source of
output for the current task.

Fixes #32047 - Match proxy actions using task_id

---

app/models/foreman_tasks/task.rb

Rename method not to get accidently confused with Action output.

Refs #31457 - rename task output messages method

---

test/unit/actions/proxy_action_test.rb

Those settings used to be nil in tests, with the SettingsRegistry they are
initialized to a default value which messes up the tests.

Fixes #32445 - Stub out settings in proxy action tests

---

app/controllers/foreman_tasks/api/tasks_controller.rb

This gets rid of the following pesky warning on each request associated with tasks:
```
___________________________________________________________________________
| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "Actions::Katello::Repository::Synchronize" for md_link([
|       md_entity("ldquo"),
|       "Actions::Katello::Repository::Synchronize",
|       md_entity("rdquo")
| ], nil)
| Available refs are []
+---------------------------------------------------------------------------
!/home/lzap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/maruku-0.7.3/lib/maruku/output/to_html.rb:656:in `to_html_link'
!/home/lzap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/maruku-0.7.3/lib/maruku/output/to_html.rb:891:in …
```

Get rid of a maruku warning

---

app/lib/actions/base.rb
app/lib/actions/middleware/load_setting_values.rb
lib/foreman_tasks/engine.rb

In Foreman we've switched to in-memory setting cache, that needs to be
reloaded on demand, Rails is doing that on every request, for dynflow
actions we need to do it on every phase.

Fixes #32729 - reload setting prior run

---

app/controllers/concerns/foreman_tasks/find_tasks_common.rb
app/controllers/foreman_tasks/api/tasks_controller.rb
app/controllers/foreman_tasks/tasks_controller.rb
test/controllers/api/tasks_controller_test.rb

Current taxonomies are not reflected within the API results, as the
search needs to be explicitly added for them, because of specifics of
Tasks taxonomy scoping - as it doesn't have direct association to
taxonomies.

Fixes #32771 - adds taxonomy scope to API results

---

lib/foreman_tasks/tasks/export_tasks.rake

HTML export used to be a two pass process. First all the tasks would be exported one by one, then all the tasks would be ordered differently, loaded again and the index would be generated. With this change, the index is being generated as tasks are being exported, removing the need for a second pass.
Also introduces a `html-dir` export format, which is the same as `html`, but produces a directory instead of a `.tar.gz`. If `$TASK_FILE` is set, it is used as a directory for the export. Adding it as a separate output format is a bit unfortunate, but it felt like the most sensible way without introducing a breaking change.

Tweaks to task export

---

app/lib/actions/proxy_action.rb
app/models/foreman_tasks/remote_task.rb
test/controllers/api/tasks_controller_test.rb
test/support/dummy_proxy_action.rb
test/unit/actions/proxy_action_test.rb
test/unit/remote_task_test.rb

The batch triggering API was introduced in 1.20, it should be available on all
releases which are not EOL.

Fixes #32024 - Drop fallback to non-batch triggering API

---

extra/foreman-tasks-cleanup.sh
lib/foreman_tasks/tasks/export_tasks.rake

- Fixes #34288 - Do not crash the task export if SKIP_FAILED is unset
- Refs #27790 - Add option validation to cleanup interface script

Fixes for interface scripts

---

app/controllers/foreman_tasks/tasks_controller.rb

After f505bb3 it is not enough for a task to be in stopped state, its locks have
to be really destroyed to count the task as unlocked.

Fixes #34343 - Unlock tasks on {force_,}unlock

---

app/models/foreman_tasks/recurring_logic.rb

when calculating next occurence time. CronParser is picky about this.

Fixes #34741 - Supply time in right time zone

---

lib/foreman_tasks/engine.rb

Rails do not handle well when namespaced models are loaded prior any unnamespaced one.
**EDIT**: please let me look smart and don't ask why :pray: 
Loading models too soon in initialization process will be imposible with Zeitwerk, so it is good practice anyway.

Fixes #34917 - do not load model constants too early

---

lib/foreman_tasks/engine.rb
package.json

This is the current version that core uses and it makes js tests green

Fixes #35052 - Update js foreman packages to 10.1

---

app/lib/actions/proxy_action.rb
app/lib/actions/trigger_proxy_batch.rb
app/models/foreman_tasks/remote_task.rb

Before we notified the local child actions that their remote counterpart
has failed, but we didn't include any details. This made the local
actions ask the smart proxy for status, get back a 404, which the local
actions did not expect.
If we know that the remote parent failed during triggering, it is clear
there will not be any remote tasks to ask about, so we can fail straight
away, without having to ask for status.

Fixes #35328 - Propagate errors when remote parent task fails

---

app/models/foreman_tasks/remote_task.rb

Consider tasks which were 'triggered' or 'parent-triggered' as running.
Steps to reproduce:
1) Start a rex job that runs for a while, `sleep 1000` works well
2) Wait for the job to get to the smart proxy
3) Kill smart proxy
4) Wait 10 minutes
Actual results: The job keeps pending, no checks to /dynflow/tasks/status going to the proxy
Expected results: One check to /dynflow/tasks/status on the proxy, the job then fails

Fixes #35592 - Fix delegated proxy task watching

---

.github/workflows/js_tests.yml

Foreman tests are only run on node versions 12,14. 
node 10 is eol for around 2 years now

update github actions node version to 12,14

---

config/routes.rb

Sidekiq >= 6.2.0 has reworked session handling, we shouldn't need to set anything and everything should just work out of the box.

Fixes #35880 - Do not configure sidekiq sessions

---

app/lib/actions/middleware/watch_delegated_proxy_sub_tasks.rb

They are meant to catch cases when the remote task stops or disappears. If this happens but the local task is already stopped, it is not an error state.

Fixes #35950 - Make delivery of ProxyActionStopped events optional

---

webpack/ForemanTasks/Components/TaskDetails/Components/TaskButtons.js
webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskButtons.test.js.snap
webpack/ForemanTasks/Components/TaskDetails/TaskDetails.js
webpack/ForemanTasks/Components/TasksTable/Components/SelectAllAlert.js
webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/SelectAllAlert.test.js.snap
webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
webpack/ForemanTasks/Components/TasksTable/TasksTable.js
webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTable.test.js.snap

It is never valid to use ```__(``)``` since string extraction relies on static strings. String interpolation breaks this, so it's best to avoid it even if the string contained is static.
This also fixes a string where interpolation should happen. This allows translations to move around the word order. Ideally they would actually properly use pluralization so that it would be "select 1 task" instead of "select 1 tasks". That would also allow other languages to properly use plurals, but that's left as a future improvement.

Fixes #35860 - Fix untranslatable strings

---

db/migrate/20211123170430_tasks_settings_to_dsl_category.rb

See:
* https://github.com/theforeman/foreman/pull/9524
* https://github.com/theforeman/foreman/pull/9524#issuecomment-1404661119

Fixes #36002 - Migration error 'column settings.category does not exist'

---

.packit.yaml

- no need to depend on the ruby module, foreman does already for us
- get current version using rubygems directly

simplify packit config

---

app/models/foreman_tasks/recurring_logic.rb
foreman-tasks.gemspec

`parse-cron` seems to be unmaintained since 2016, `fugit` seems to be still active. In addition to that, it should also allow expressing intervals such as "first Monday each month" which wasn't possible with `parse-cron`.
TODO:

Replace parse-cron with fugit

---

app/models/foreman_tasks/recurring_logic.rb
test/unit/recurring_logic_test.rb

Based on documentation, do_parse seems like a better fit for us.
https://github.com/floraison/fugit#fugitdo_parses

Fixes #36392 - Replace fugit.parse with fugit.do_parse

---

app/lib/actions/check_long_running_tasks.rb
app/lib/actions/deliver_long_running_tasks_notification.rb
app/mailers/tasks_mailer.rb
app/models/foreman_tasks/tasks_mail_notification.rb
app/services/ui_notifications/tasks/tasks_running_long.rb
app/views/tasks_mailer/long_tasks.html.erb
app/views/tasks_mailer/long_tasks.text.erb
db/seeds.d/30-notification_blueprints.rb
db/seeds.d/95-mail_notifications.rb
lib/foreman_tasks.rb
lib/foreman_tasks/engine.rb
lib/foreman_tasks/tasks/reschedule_long_running_tasks_checker.rake

- users are able to opt-in/opt-out in email preferences
- toast notification is now tied to the email notification which isn't exactly great, but we don't really have any other means of configuring it
- ~~this is tricky. I thought I'd add a migration, but the migration needs to run after data (the template) is seeded. Currently the migration creates the template and then the seeds override it. I'm not particularly fond of this, but I don't really see another way~~
- done, sort of. We don't really have the means for doing this nicely as recurring logics cannot be edited
- by default set to midnight
- However, as a workaround the RL can be cancelled, env variable `FOREMAN_TASKS_CHECK_LONG_RUNNING_TASKS_CRONLINE` can be set to a new cronline and then on service restart the RL should get …

Fixes #36351 - Send out email notification when tasks linger in running or paused for longer than two days

---

app/lib/actions/action_with_sub_plans.rb
app/lib/actions/bulk_action.rb
foreman-tasks.gemspec
test/unit/actions/action_with_sub_plans_test.rb
test/unit/task_groups_test.rb

In addition to migrating to a newer implementation, it also exposes concurrency limiting for sub-plans spawned by `::Actions::BulkAction`
Requires:
- https://github.com/Dynflow/dynflow/pull/428
TODO:

Fixes #36700 - Switch to v2 of sub plans

---

app/lib/actions/check_long_running_tasks.rb
app/lib/actions/deliver_long_running_tasks_notification.rb

Without this change the execution plan would go into paused and then would be picked up by subsequent checks, which would then go into paused and so on and so on.

Fixes #36746 - Make email delivery skip on failures

---

app/lib/actions/check_long_running_tasks.rb
app/models/foreman_tasks/concerns/user_extensions.rb
db/seeds.d/95-mail_notifications.rb

- enabled for admin-like users on create
- enabled for admin-like users on seed when the notifications is first created, excluding hidden admins
- delivery is not attempted for disabled users
- delivery is not attempted for users without email set
- delivery is attempted only for users with mail_enabled set

Fixes #36848 - Rework long running task watching setup

---

app/models/foreman_tasks/concerns/user_extensions.rb

Returning early if we're seeding should be safe, under the assumtion there is no admin user that gets seeded after the notification itself, because the notification attaches itself to admins explicitly when it is created and does not rely on the before verification callback.
It should now survive when the org admin role does not exist.

Refs #36848 - Disable mail setting hook when in seeds

---

app/lib/actions/bulk_action.rb
test/unit/actions/bulk_action_test.rb

This is not ideal, but it should be in line with what we had before the move to v2 bulk actions.
To handle this properly, the changes will need to start in Dynflow and then in things that build on top of it. This is something we might ultimately have to do for Ruby 3.

Fixes #36931 - Pass keywords around the old way

---

app/lib/actions/trigger_proxy_batch.rb
test/unit/actions/trigger_proxy_batch_test.rb

Now it should be more strict about when it finishes. Previously this action could finish too early, even before everything was dispatched to the proxy.

Fixes #36937 - Rework proxy batch triggering

---

lib/foreman_tasks/engine.rb
webpack/ForemanTasks/Components/TasksTable/TasksIndexPage.js
webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js

The Tasks page had multiple titles because of the usage of breadcrumb as a title in the PageLayout. It is dependent on https://github.com/theforeman/foreman/pull/9830.

Fixes #20391 - Hide breadcrumb title from Tasks page

---

.github/workflows/ruby_tests.yml
lib/foreman_tasks/tasks/test.rake

This is an effort to align all plugin testing on reusable workflows. For now this is mostly testing if I've missed something, so I'm going over the various plugins.

Rewrite to a shared GitHub Actions workflow

---

app/controllers/foreman_tasks/tasks_controller.rb
app/models/foreman_tasks/task/dynflow_task.rb
foreman-tasks.gemspec

Requires https://github.com/Dynflow/dynflow/pull/406

Fixes #34344 - Add support for halting

---

webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsActions.test.js

its not needed as the mock is loaded from webpack/__mocks__/foremanReact/redux/API/index.js

Fixes #37608 - cleanup TaskDetailsActions.test.js api mock

---

app/lib/actions/middleware/keep_current_request_id.rb
lib/foreman_tasks/engine.rb
test/lib/actions/middleware/keep_current_request_id_test.rb

Fixes #37452 - Support Zeitwerk loader

---

lib/foreman_tasks.rb

Not sure if this requires opening an issue :grin:

Fix exception name

---

lib/foreman_tasks/engine.rb

I'll file an issue later :)
Found that `reload!` via Rails console was broken in Katello. One reason came from this plugin:
```
Foreman::Exception: ERF42-8739 [Foreman::Exception]: Setting 'foreman_tasks_sync_task_timeout' is already defined, please avoid collisions
from /home/vagrant/foreman/app/registries/foreman/setting_manager.rb:124:in `setting'
```
This happens even in an environment where it's the only plugin: 
```
[1] pry(main)> Foreman::Plugin.registered_plugins.keys
=> [:"foreman-tasks"]
```
The design of the plugin registry is that it's built once at app load. The registry survives code reloading which is why the above error shows up. Seems like this broke in #752. 
The fix is to perform only the application-code dependent plugin work inside `reloader.to_prepare` and move the …

 Fixes #38437 - Separate application code from plugin registration

---

webpack/ForemanTasks/Components/TasksDashboard/Components/TasksLabelsRow/TasksLabelsRow.scss
webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.scss

css imports were moved in https://github.com/theforeman/foreman/pull/10345 already
and will break after https://github.com/theforeman/foreman/pull/10342 is merged.
This pr is only for the css import and can be merged now

Fixes #37908 - move css import from vendor to foreman

---

app/models/foreman_tasks/triggering.rb
test/unit/triggering_test.rb

Validations are only run if the mode is future or recurring (ie. if start_at plays some roles) and only when the attribute actually changed.

Refs #37938 - Saner start_at handling

---

lib/foreman_tasks/engine.rb
test/unit/tasks_setting_test.rb

Added custom validation to the Tasks troubleshooting URL settings.
Had to replace the label and version since we replace them in the usage:
```ruby
url_template = Setting[:foreman_tasks_troubleshooting_url]
return if url_template.blank?
url = url_template % { label: generic_only ? '' : link_anchor, version: SETTINGS[:version].
```

Fixes #38758 - Validate Tasks troubleshooting URL settings value
